### ISSUE TITLE
minor: left plot set_ylim(0,360)

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/jwst_coronagraph_visibility#11]
subject line says it all - this is in degrees so having matplotlib autoscale the y axis to 0-400 isn't helpful.

**Comment by josePhoenix** [comment]
It's scaled on purpose, actually, as picking points at the extrema was difficult with 0-360º

**Comment by mperrin** [comment]
oh ok then, never mind!

**Comment by josePhoenix** [comment]
I can't find a case where *does* exceed abut a border with [0, 360], so it's possible I gave myself more margin than necessary when I overrode the autoscaling.
