### ISSUE TITLE
Support for moving objects

### ISSUE THREAD

**Issue by migueldvb** [spacetelescope/jwst_coronagraph_visibility#14]
It would be useful to determine observability for moving objects using an ephemeris from JPL HORIZONS.

**Comment by josePhoenix** [comment]
@migueldvb It seems like that request is better suited for https://github.com/spacetelescope/jwst_gtvt, as it does not have to do with the coronagraph modes. This tool is specifically to address the inability to explore the impact of roll angle constraints on companion targets around coronagraph masks intuitively in APT.
