### ISSUE TITLE
Start date missing?

### ISSUE THREAD

**Issue by abhijithrajan** [spacetelescope/jwst_coronagraph_visibility#16]
Hello, 

I have installed v0.3.0 via astroconda and am missing the Start Date option in the gui. 

<img width="252" alt="screen shot 2017-08-01 at 11 55 56 am" src="https://user-images.githubusercontent.com/1957246/28841863-6d9004c0-76b0-11e7-8e46-1af2d60a22a4.png">

The tutorial for the CVT suggests that it should be possible to choose the start date, a pretty useful option (https://jwst-docs.stsci.edu/display/JPP/JWST+Coronagraphic+Visibility+Tool+Help). The tutorial was written for v0.1.0, so has the start date been removed from the tool or is there a way to ensure that I can choose what date to generate the visibilities from. 

Thanks

**Comment by josePhoenix** [comment]
I'll alert our documentation people that that needs to be revised. The elongation curve is (almost) exactly the same from year to year, so the start date option served only to offset the phase of the curve. in the plot. I believe the functionality is still in there (though not exposed in the GUI), so we could consider bringing it back.

**Comment by josePhoenix** [comment]
Actually, upon review, I'm not seeing any mention of that control in the documentation. Could you quote the relevant bit?

**Comment by abhijithrajan** [comment]
Actually I'm not sure if the Start Date of Oct 1, 2018 is an option that could be changed or if it was just set to show dates after Oct 1.

<img width="693" alt="screen shot 2017-08-01 at 12 03 22 pm" src="https://user-images.githubusercontent.com/1957246/28842159-748d2928-76b1-11e7-9d2e-87cf54b3f260.png">

**Comment by josePhoenix** [comment]
The current version starts from January 1 and omits the year to avoid confusion. We can certainly update that screenshot, though!

**Comment by abhijithrajan** [comment]
Ok thanks. I wasn't sure if that was something we could modify 👍. Though I think you'll need to update all the screenshots, or clarify that the start date has been removed since I believe it shows up in all the images.

**Comment by juliengirard** [comment]
I think we can close this issue
